### ISSUE TITLE
Users should able to signup/login to our API. 

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/api#13]
Our main aim should be to allow users to signup with their unique **username**. We will also have to store email but then we will also have to check if the email is legit or not. 

## TODO
- [ ] Connect database
- [ ] Create user schema, that will easy to change in the future. 
- [ ] Create login and signup routes 
- [ ] Also create Login and sigup views.

**Comment by Souvikns** [comment]
Will close this issue after I have tested the code.
