### ISSUE TITLE
Github Authentication

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/api#3]
We are just gonna have a login with GitHub feature. 

## TODO
- [ ] Hook up passportjs and use passport-github strategy.
- [ ] Create suitable authentication route. 
- [ ] Create suitable middleware function.

**Comment by Souvikns** [comment]
@imabp before you start building the authentication we should build the user schema as we have to store the user data after successful signup, and before that, we do need to integrate the database, so I think you should start working on this issue after #7 has been closed.
